// config.js
module.exports = {
    DISCORD_TOKEN: 'YOUR_DISCORD_BOT_TOKEN',
    CLIENT_ID: 'YOUR_DISCORD_CLIENT_ID',
    SPOTIFY_CLIENT_ID: 'YOUR_SPOTIFY_CLIENT_ID',
    SPOTIFY_CLIENT_SECRET: 'YOUR_SPOTIFY_CLIENT_SECRET'
};
